"""Successor-aware historical views for immutable QW-LC4-E stage tests."""

from __future__ import annotations

import base64
import shutil
import sys
from pathlib import Path

import pytest

_PRE_CALLSITE_TEST_FILES = {
    "test_stage3b_qwake_lc4_final_execution_acknowledgement_materialization_"
    "invocation_operation_implementation.py",
    "test_stage3b_qwake_lc4_final_execution_acknowledgement_materialization_"
    "invocation_operation_callsite_authoring.py",
}
_PRE_AUTHORIZATION_TEST_FILES = {
    "test_stage3b_qwake_lc4_final_execution_acknowledgement_materialization_"
    "invocation_operation_callsite_implementation.py",
    "test_stage3b_qwake_lc4_final_execution_acknowledgement_materialization_"
    "invocation_operation_callsite_execution_authoring.py",
}
_PRE_ATTEMPT003_FREEZE_TEST_FILES = {
    "test_stage3b_qwake_attempt_003_execution_freeze_materialization.py",
    "test_stage3b_qwake_lc4_final_execution_acknowledgement_materialization_"
    "invocation_operation_callsite_execution_authorization.py",
}

_PRODUCTION_CALLSITE = Path(
    "scripts/invoke_stage3b_qwake_lc4_final_execution_acknowledgement_"
    "materialization_operation.py"
)
_EXECUTION_AUTHORIZATION_PACKAGE = Path(
    "experiments/frozen/stage3b-qwake-lc4-e-final-execution-"
    "acknowledgement-materialization-invocation-operation-callsite-execution-"
    "authorization-v1"
)
_ATTEMPT003_EXECUTION_FREEZE_PACKAGE = Path(
    "experiments/frozen/stage3b-qwake-attempt-003-execution-freeze-v1"
)
_ATTEMPT003_AUTHORIZATION_PACKAGE = Path(
    "experiments/frozen/stage3b-qwake-attempt-003-authorization-v1"
)

_HISTORICAL_CONFTEST_BYTES = base64.b64decode(
    "IiIiU3VjY2Vzc29yLWF3YXJlIGhpc3RvcmljYWwgdmlld3MgZm9yIGltbXV0YWJsZSBRVy1MQzQtRSBzdGFnZSB0ZXN0cy4iIiIKCmZyb20gX19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnMKCmltcG9ydCBzaHV0aWwKaW1wb3J0IHN5cwpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKCmltcG9ydCBweXRlc3QKCl9ISVNUT1JJQ0FMX1RFU1RfRklMRVMgPSB7CiAgICAidGVzdF9zdGFnZTNiX3F3YWtlX2xjNF9maW5hbF9leGVjdXRpb25fYWNrbm93bGVkZ2VtZW50X21hdGVyaWFsaXphdGlvbl8iCiAgICAiaW52b2NhdGlvbl9vcGVyYXRpb25faW1wbGVtZW50YXRpb24ucHkiLAogICAgInRlc3Rfc3RhZ2UzYl9xd2FrZV9sYzRfZmluYWxfZXhlY3V0aW9uX2Fja25vd2xlZGdlbWVudF9tYXRlcmlhbGl6YXRpb25fIgogICAgImludm9jYXRpb25fb3BlcmF0aW9uX2NhbGxzaXRlX2F1dGhvcmluZy5weSIsCn0KX1BST0RVQ1RJT05fQ0FMTFNJVEUgPSBQYXRoKAogICAgInNjcmlwdHMvaW52b2tlX3N0YWdlM2JfcXdha2VfbGM0X2ZpbmFsX2V4ZWN1dGlvbl9hY2tub3dsZWRnZW1lbnRfIgogICAgIm1hdGVyaWFsaXphdGlvbl9vcGVyYXRpb24ucHkiCikKCgpAcHl0ZXN0LmZpeHR1cmUoc2NvcGU9InNlc3Npb24iLCBhdXRvdXNlPVRydWUpCmRlZiBfaGlzdG9yaWNhbF9xd2FrZV9zdGFnZV92aWV3cygKICAgIHRtcF9wYXRoX2ZhY3Rvcnk6IHB5dGVzdC5UZW1wUGF0aEZhY3RvcnksCik6CiAgICByb290ID0gUGF0aChfX2ZpbGVfXykucmVzb2x2ZSgpLnBhcmVudHNbMV0KICAgIGhpc3RvcmljYWxfcm9vdCA9IHRtcF9wYXRoX2ZhY3RvcnkubWt0ZW1wKCJxd2FrZS1oaXN0b3JpY2FsLXN0YWdlLXZpZXciKSAvICJyZXBvc2l0b3J5IgogICAgc2h1dGlsLmNvcHl0cmVlKAogICAgICAgIHJvb3QsCiAgICAgICAgaGlzdG9yaWNhbF9yb290LAogICAgICAgIGlnbm9yZT1zaHV0aWwuaWdub3JlX3BhdHRlcm5zKAogICAgICAgICAgICAiLmdpdCIsCiAgICAgICAgICAgICIubXlweV9jYWNoZSIsCiAgICAgICAgICAgICIucHl0ZXN0X2NhY2hlIiwKICAgICAgICAgICAgIi5ydWZmX2NhY2hlIiwKICAgICAgICAgICAgIl9fcHljYWNoZV9fIiwKICAgICAgICAgICAgInNpdGUiLAogICAgICAgICAgICAic2l0ZV9ydSIsCiAgICAgICAgICAgICJzaXRlX2VuIiwKICAgICAgICApLAogICAgKQogICAgY2FsbHNpdGUgPSBoaXN0b3JpY2FsX3Jvb3QgLyBfUFJPRFVDVElPTl9DQUxMU0lURQogICAgaWYgY2FsbHNpdGUuZXhpc3RzKCkgb3IgY2FsbHNpdGUuaXNfc3ltbGluaygpOgogICAgICAgIGNhbGxzaXRlLnVubGluaygpCgogICAgcHJldmlvdXM6IGRpY3Rbc3RyLCBQYXRoXSA9IHt9CiAgICBmb3IgbW9kdWxlX25hbWUsIG1vZHVsZSBpbiB0dXBsZShzeXMubW9kdWxlcy5pdGVtcygpKToKICAgICAgICBtb2R1bGVfZmlsZSA9IGdldGF0dHIobW9kdWxlLCAiX19maWxlX18iLCBOb25lKQogICAgICAgIGlmIG1vZHVsZV9maWxlIGlzIE5vbmUgb3Igbm90IGhhc2F0dHIobW9kdWxlLCAiUk9PVCIpOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGlmIFBhdGgobW9kdWxlX2ZpbGUpLm5hbWUgbm90IGluIF9ISVNUT1JJQ0FMX1RFU1RfRklMRVM6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgcHJldmlvdXNbbW9kdWxlX25hbWVdID0gbW9kdWxlLlJPT1QKICAgICAgICBtb2R1bGUuUk9PVCA9IGhpc3RvcmljYWxfcm9vdAoKICAgIHlpZWxkCgogICAgZm9yIG1vZHVsZV9uYW1lLCBvcmlnaW5hbF9yb290IGluIHByZXZpb3VzLml0ZW1zKCk6CiAgICAgICAgbW9kdWxlID0gc3lzLm1vZHVsZXMuZ2V0KG1vZHVsZV9uYW1lKQogICAgICAgIGlmIG1vZHVsZSBpcyBub3QgTm9uZToKICAgICAgICAgICAgbW9kdWxlLlJPT1QgPSBvcmlnaW5hbF9yb290Cg=="
)
_PRE_ATTEMPT003_FREEZE_CONFTEST_BYTES = base64.b64decode(
    "IiIiU3VjY2Vzc29yLWF3YXJlIGhpc3RvcmljYWwgdmlld3MgZm9yIGltbXV0YWJsZSBRVy1MQzQtRSBzdGFnZSB0ZXN0cy4iIiIKCmZyb20gX19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnMKCmltcG9ydCBiYXNlNjQKaW1wb3J0IHNodXRpbAppbXBvcnQgc3lzCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKaW1wb3J0IHB5dGVzdAoKX1BSRV9DQUxMU0lURV9URVNUX0ZJTEVTID0gewogICAgInRlc3Rfc3RhZ2UzYl9xd2FrZV9sYzRfZmluYWxfZXhlY3V0aW9uX2Fja25vd2xlZGdlbWVudF9tYXRlcmlhbGl6YXRpb25fIgogICAgImludm9jYXRpb25fb3BlcmF0aW9uX2ltcGxlbWVudGF0aW9uLnB5IiwKICAgICJ0ZXN0X3N0YWdlM2JfcXdha2VfbGM0X2ZpbmFsX2V4ZWN1dGlvbl9hY2tub3dsZWRnZW1lbnRfbWF0ZXJpYWxpemF0aW9uXyIKICAgICJpbnZvY2F0aW9uX29wZXJhdGlvbl9jYWxsc2l0ZV9hdXRob3JpbmcucHkiLAp9Cl9QUkVfQVVUSE9SSVpBVElPTl9URVNUX0ZJTEVTID0gewogICAgInRlc3Rfc3RhZ2UzYl9xd2FrZV9sYzRfZmluYWxfZXhlY3V0aW9uX2Fja25vd2xlZGdlbWVudF9tYXRlcmlhbGl6YXRpb25fIgogICAgImludm9jYXRpb25fb3BlcmF0aW9uX2NhbGxzaXRlX2ltcGxlbWVudGF0aW9uLnB5IiwKICAgICJ0ZXN0X3N0YWdlM2JfcXdha2VfbGM0X2ZpbmFsX2V4ZWN1dGlvbl9hY2tub3dsZWRnZW1lbnRfbWF0ZXJpYWxpemF0aW9uXyIKICAgICJpbnZvY2F0aW9uX29wZXJhdGlvbl9jYWxsc2l0ZV9leGVjdXRpb25fYXV0aG9yaW5nLnB5IiwKfQpfUFJPRFVDVElPTl9DQUxMU0lURSA9IFBhdGgoCiAgICAic2NyaXB0cy9pbnZva2Vfc3RhZ2UzYl9xd2FrZV9sYzRfZmluYWxfZXhlY3V0aW9uX2Fja25vd2xlZGdlbWVudF8iCiAgICAibWF0ZXJpYWxpemF0aW9uX29wZXJhdGlvbi5weSIKKQpfRVhFQ1VUSU9OX0FVVEhPUklaQVRJT05fUEFDS0FHRSA9IFBhdGgoCiAgICAiZXhwZXJpbWVudHMvZnJvemVuL3N0YWdlM2ItcXdha2UtbGM0LWUtZmluYWwtZXhlY3V0aW9uLSIKICAgICJhY2tub3dsZWRnZW1lbnQtbWF0ZXJpYWxpemF0aW9uLWludm9jYXRpb24tb3BlcmF0aW9uLWNhbGxzaXRlLWV4ZWN1dGlvbi0iCiAgICAiYXV0aG9yaXphdGlvbi12MSIKKQoKX0hJU1RPUklDQUxfQ09ORlRFU1RfQllURVMgPSBiYXNlNjQuYjY0ZGVjb2RlKAogICAgIklpSWlVM1ZqWTJWemMyOXlMV0YzWVhKbElHaHBjM1J2Y21sallXd2dkbWxsZDNNZ1ptOXlJR2x0YlhWMFlXSnNaU0JSVnkxTVF6UXRSU0J6ZEdGblpTQjBaWE4wY3k0aUlpSUtDbVp5YjIwZ1gxOW1kWFIxY21WZlh5QnBiWEJ2Y25RZ1lXNXViM1JoZEdsdmJuTUtDbWx0Y0c5eWRDQnphSFYwYVd3S2FXMXdiM0owSUhONWN3cG1jbTl0SUhCaGRHaHNhV0lnYVcxd2IzSjBJRkJoZEdnS0NtbHRjRzl5ZENCd2VYUmxjM1FLQ2w5SVNWTlVUMUpKUTBGTVgxUkZVMVJmUmtsTVJWTWdQU0I3Q2lBZ0lDQWlkR1Z6ZEY5emRHRm5aVE5pWDNGM1lXdGxYMnhqTkY5bWFXNWhiRjlsZUdWamRYUnBiMjVmWVdOcmJtOTNiR1ZrWjJWdFpXNTBYMjFoZEdWeWFXRnNhWHBoZEdsdmJsOGlDaUFnSUNBaWFXNTJiMk5oZEdsdmJsOXZjR1Z5WVhScGIyNWZhVzF3YkdWdFpXNTBZWFJwYjI0dWNIa2lMQW9nSUNBZ0luUmxjM1JmYzNSaFoyVXpZbDl4ZDJGclpWOXNZelJmWm1sdVlXeGZaWGhsWTNWMGFXOXVYMkZqYTI1dmQyeGxaR2RsYldWdWRGOXRZWFJsY21saGJHbDZZWFJwYjI1Zklnb2dJQ0FnSW1sdWRtOWpZWFJwYjI1ZmIzQmxjbUYwYVc5dVgyTmhiR3h6YVhSbFgyRjFkR2h2Y21sdVp5NXdlU0lzQ24wS1gxQlNUMFJWUTFSSlQwNWZRMEZNVEZOSlZFVWdQU0JRWVhSb0tBb2dJQ0FnSW5OamNtbHdkSE12YVc1MmIydGxYM04wWVdkbE0ySmZjWGRoYTJWZmJHTTBYMlpwYm1Gc1gyVjRaV04xZEdsdmJsOWhZMnR1YjNkc1pXUm5aVzFsYm5SZklnb2dJQ0FnSW0xaGRHVnlhV0ZzYVhwaGRHbHZibDl2Y0dWeVlYUnBiMjR1Y0hraUNpa0tDZ3BBY0hsMFpYTjBMbVpwZUhSMWNtVW9jMk52Y0dVOUluTmxjM05wYjI0aUxDQmhkWFJ2ZFhObFBWUnlkV1VwQ21SbFppQmZhR2x6ZEc5eWFXTmhiRjl4ZDJGclpWOXpkR0ZuWlY5MmFXVjNjeWdLSUNBZ0lIUnRjRjl3WVhSb1gyWmhZM1J2Y25rNklIQjVkR1Z6ZEM1VVpXMXdVR0YwYUVaaFkzUnZjbmtzQ2lrNkNpQWdJQ0J5YjI5MElEMGdVR0YwYUNoZlgyWnBiR1ZmWHlrdWNtVnpiMngyWlNncExuQmhjbVZ1ZEhOYk1WMEtJQ0FnSUdocGMzUnZjbWxqWVd4ZmNtOXZkQ0E5SUhSdGNGOXdZWFJvWDJaaFkzUnZjbmt1Yld0MFpXMXdLQ0p4ZDJGclpTMW9hWE4wYjNKcFkyRnNMWE4wWVdkbExYWnBaWGNpS1NBdklDSnlaWEJ2YzJsMGIzSjVJZ29nSUNBZ2MyaDFkR2xzTG1OdmNIbDBjbVZsS0FvZ0lDQWdJQ0FnSUhKdmIzUXNDaUFnSUNBZ0lDQWdhR2x6ZEc5eWFXTmhiRjl5YjI5MExBb2dJQ0FnSUNBZ0lHbG5ibTl5WlQxemFIVjBhV3d1YVdkdWIzSmxYM0JoZEhSbGNtNXpLQW9nSUNBZ0lDQWdJQ0FnSUNBaUxtZHBkQ0lzQ2lBZ0lDQWdJQ0FnSUNBZ0lDSXViWGx3ZVY5allXTm9aU0lzQ2lBZ0lDQWdJQ0FnSUNBZ0lDSXVjSGwwWlhOMFgyTmhZMmhsSWl3S0lDQWdJQ0FnSUNBZ0lDQWdJaTV5ZFdabVgyTmhZMmhsSWl3S0lDQWdJQ0FnSUNBZ0lDQWdJbDlmY0hsallXTm9aVjlmSWl3S0lDQWdJQ0FnSUNBZ0lDQWdJbk5wZEdVaUxBb2dJQ0FnSUNBZ0lDQWdJQ0FpYzJsMFpWOXlkU0lzQ2lBZ0lDQWdJQ0FnSUNBZ0lDSnphWFJsWDJWdUlpd0tJQ0FnSUNBZ0lDQXBMQW9nSUNBZ0tRb2dJQ0FnWTJGc2JITnBkR1VnUFNCb2FYTjBiM0pwWTJGc1gzSnZiM1FnTHlCZlVGSlBSRlZEVkVsUFRsOURRVXhNVTBsVVJRb2dJQ0FnYVdZZ1kyRnNiSE5wZEdVdVpYaHBjM1J6S0NrZ2IzSWdZMkZzYkhOcGRHVXVhWE5mYzNsdGJHbHVheWdwT2dvZ0lDQWdJQ0FnSUdOaGJHeHphWFJsTG5WdWJHbHVheWdwQ2dvZ0lDQWdjSEpsZG1sdmRYTTZJR1JwWTNSYmMzUnlMQ0JRWVhSb1hTQTlJSHQ5Q2lBZ0lDQm1iM0lnYlc5a2RXeGxYMjVoYldVc0lHMXZaSFZzWlNCcGJpQjBkWEJzWlNoemVYTXViVzlrZFd4bGN5NXBkR1Z0Y3lncEtUb0tJQ0FnSUNBZ0lDQnRiMlIxYkdWZlptbHNaU0E5SUdkbGRHRjBkSElvYlc5a2RXeGxMQ0FpWDE5bWFXeGxYMThpTENCT2IyNWxLUW9nSUNBZ0lDQWdJR2xtSUcxdlpIVnNaVjltYVd4bElHbHpJRTV2Ym1VZ2IzSWdibTkwSUdoaGMyRjBkSElvYlc5a2RXeGxMQ0FpVWs5UFZDSXBPZ29nSUNBZ0lDQWdJQ0FnSUNCamIyNTBhVzUxWlFvZ0lDQWdJQ0FnSUdsbUlGQmhkR2dvYlc5a2RXeGxYMlpwYkdVcExtNWhiV1VnYm05MElHbHVJRjlJU1ZOVVQxSkpRMEZNWDFSRlUxUmZSa2xNUlZNNkNpQWdJQ0FnSUNBZ0lDQWdJR052Ym5ScGJuVmxDaUFnSUNBZ0lDQWdjSEpsZG1sdmRYTmJiVzlrZFd4bFgyNWhiV1ZkSUQwZ2JXOWtkV3hsTGxKUFQxUUtJQ0FnSUNBZ0lDQnRiMlIxYkdVdVVrOVBWQ0E5SUdocGMzUnZjbWxqWVd4ZmNtOXZkQW9LSUNBZ0lIbHBaV3hrQ2dvZ0lDQWdabTl5SUcxdlpIVnNaVjl1WVcxbExDQnZjbWxuYVc1aGJGOXliMjkwSUdsdUlIQnlaWFpwYjNWekxtbDBaVzF6S0NrNkNpQWdJQ0FnSUNBZ2JXOWtkV3hsSUQwZ2MzbHpMbTF2WkhWc1pYTXVaMlYwS0cxdlpIVnNaVjl1WVcxbEtRb2dJQ0FnSUNBZ0lHbG1JRzF2WkhWc1pTQnBjeUJ1YjNRZ1RtOXVaVG9LSUNBZ0lDQWdJQ0FnSUNBZ2JXOWtkV3hsTGxKUFQxUWdQU0J2Y21sbmFXNWhiRjl5YjI5MENnPT0iCikKCgpkZWYgX2NvcHlfcmVwb3NpdG9yeShyb290OiBQYXRoLCB0YXJnZXQ6IFBhdGgpIC0+IFBhdGg6CiAgICBzaHV0aWwuY29weXRyZWUoCiAgICAgICAgcm9vdCwKICAgICAgICB0YXJnZXQsCiAgICAgICAgaWdub3JlPXNodXRpbC5pZ25vcmVfcGF0dGVybnMoCiAgICAgICAgICAgICIuZ2l0IiwKICAgICAgICAgICAgIi5teXB5X2NhY2hlIiwKICAgICAgICAgICAgIi5weXRlc3RfY2FjaGUiLAogICAgICAgICAgICAiLnJ1ZmZfY2FjaGUiLAogICAgICAgICAgICAiX19weWNhY2hlX18iLAogICAgICAgICAgICAic2l0ZSIsCiAgICAgICAgICAgICJzaXRlX3J1IiwKICAgICAgICAgICAgInNpdGVfZW4iLAogICAgICAgICksCiAgICApCiAgICByZXR1cm4gdGFyZ2V0CgoKQHB5dGVzdC5maXh0dXJlKHNjb3BlPSJzZXNzaW9uIiwgYXV0b3VzZT1UcnVlKQpkZWYgX2hpc3RvcmljYWxfcXdha2Vfc3RhZ2Vfdmlld3MoCiAgICB0bXBfcGF0aF9mYWN0b3J5OiBweXRlc3QuVGVtcFBhdGhGYWN0b3J5LAopOgogICAgcm9vdCA9IFBhdGgoX19maWxlX18pLnJlc29sdmUoKS5wYXJlbnRzWzFdCiAgICBiYXNlID0gdG1wX3BhdGhfZmFjdG9yeS5ta3RlbXAoInF3YWtlLWhpc3RvcmljYWwtc3RhZ2Utdmlld3MiKQoKICAgIHByZV9jYWxsc2l0ZV9yb290ID0gX2NvcHlfcmVwb3NpdG9yeShyb290LCBiYXNlIC8gInByZS1jYWxsc2l0ZSIpCiAgICAocHJlX2NhbGxzaXRlX3Jvb3QgLyAidGVzdHMvY29uZnRlc3QucHkiKS53cml0ZV9ieXRlcygKICAgICAgICBfSElTVE9SSUNBTF9DT05GVEVTVF9CWVRFUwogICAgKQogICAgY2FsbHNpdGUgPSBwcmVfY2FsbHNpdGVfcm9vdCAvIF9QUk9EVUNUSU9OX0NBTExTSVRFCiAgICBpZiBjYWxsc2l0ZS5leGlzdHMoKSBvciBjYWxsc2l0ZS5pc19zeW1saW5rKCk6CiAgICAgICAgY2FsbHNpdGUudW5saW5rKCkKCiAgICBwcmVfYXV0aG9yaXphdGlvbl9yb290ID0gX2NvcHlfcmVwb3NpdG9yeShyb290LCBiYXNlIC8gInByZS1hdXRob3JpemF0aW9uIikKICAgIChwcmVfYXV0aG9yaXphdGlvbl9yb290IC8gInRlc3RzL2NvbmZ0ZXN0LnB5Iikud3JpdGVfYnl0ZXMoCiAgICAgICAgX0hJU1RPUklDQUxfQ09ORlRFU1RfQllURVMKICAgICkKICAgIGF1dGhvcml6YXRpb25fcGFja2FnZSA9IHByZV9hdXRob3JpemF0aW9uX3Jvb3QgLyBfRVhFQ1VUSU9OX0FVVEhPUklaQVRJT05fUEFDS0FHRQogICAgaWYgYXV0aG9yaXphdGlvbl9wYWNrYWdlLmV4aXN0cygpIG9yIGF1dGhvcml6YXRpb25fcGFja2FnZS5pc19zeW1saW5rKCk6CiAgICAgICAgc2h1dGlsLnJtdHJlZShhdXRob3JpemF0aW9uX3BhY2thZ2UpCgogICAgcHJldmlvdXM6IGRpY3Rbc3RyLCBQYXRoXSA9IHt9CiAgICBmb3IgbW9kdWxlX25hbWUsIG1vZHVsZSBpbiB0dXBsZShzeXMubW9kdWxlcy5pdGVtcygpKToKICAgICAgICBtb2R1bGVfZmlsZSA9IGdldGF0dHIobW9kdWxlLCAiX19maWxlX18iLCBOb25lKQogICAgICAgIGlmIG1vZHVsZV9maWxlIGlzIE5vbmUgb3Igbm90IGhhc2F0dHIobW9kdWxlLCAiUk9PVCIpOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGZpbGVuYW1lID0gUGF0aChtb2R1bGVfZmlsZSkubmFtZQogICAgICAgIHJlcGxhY2VtZW50OiBQYXRoIHwgTm9uZSA9IE5vbmUKICAgICAgICBpZiBmaWxlbmFtZSBpbiBfUFJFX0NBTExTSVRFX1RFU1RfRklMRVM6CiAgICAgICAgICAgIHJlcGxhY2VtZW50ID0gcHJlX2NhbGxzaXRlX3Jvb3QKICAgICAgICBlbGlmIGZpbGVuYW1lIGluIF9QUkVfQVVUSE9SSVpBVElPTl9URVNUX0ZJTEVTOgogICAgICAgICAgICByZXBsYWNlbWVudCA9IHByZV9hdXRob3JpemF0aW9uX3Jvb3QKICAgICAgICBpZiByZXBsYWNlbWVudCBpcyBOb25lOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIHByZXZpb3VzW21vZHVsZV9uYW1lXSA9IG1vZHVsZS5ST09UCiAgICAgICAgbW9kdWxlLlJPT1QgPSByZXBsYWNlbWVudAoKICAgIHlpZWxkCgogICAgZm9yIG1vZHVsZV9uYW1lLCBvcmlnaW5hbF9yb290IGluIHByZXZpb3VzLml0ZW1zKCk6CiAgICAgICAgbW9kdWxlID0gc3lzLm1vZHVsZXMuZ2V0KG1vZHVsZV9uYW1lKQogICAgICAgIGlmIG1vZHVsZSBpcyBub3QgTm9uZToKICAgICAgICAgICAgbW9kdWxlLlJPT1QgPSBvcmlnaW5hbF9yb290Cg=="
)


def _copy_repository(root: Path, target: Path) -> Path:
    shutil.copytree(
        root,
        target,
        ignore=shutil.ignore_patterns(
            ".git",
            ".mypy_cache",
            ".pytest_cache",
            ".ruff_cache",
            "__pycache__",
            "site",
            "site_ru",
            "site_en",
        ),
    )
    return target


@pytest.fixture(scope="session", autouse=True)
def _historical_qwake_stage_views(
    tmp_path_factory: pytest.TempPathFactory,
):
    root = Path(__file__).resolve().parents[1]
    base = tmp_path_factory.mktemp("qwake-historical-stage-views")

    pre_callsite_root = _copy_repository(root, base / "pre-callsite")
    (pre_callsite_root / "tests/conftest.py").write_bytes(
        _HISTORICAL_CONFTEST_BYTES
    )
    callsite = pre_callsite_root / _PRODUCTION_CALLSITE
    if callsite.exists() or callsite.is_symlink():
        callsite.unlink()

    pre_authorization_root = _copy_repository(root, base / "pre-authorization")
    (pre_authorization_root / "tests/conftest.py").write_bytes(
        _HISTORICAL_CONFTEST_BYTES
    )
    authorization_package = pre_authorization_root / _EXECUTION_AUTHORIZATION_PACKAGE
    if authorization_package.exists() or authorization_package.is_symlink():
        shutil.rmtree(authorization_package)

    pre_attempt003_freeze_root = _copy_repository(
        root,
        base / "pre-attempt003-freeze",
    )
    (pre_attempt003_freeze_root / "tests/conftest.py").write_bytes(
        _PRE_ATTEMPT003_FREEZE_CONFTEST_BYTES
    )
    attempt003_freeze_package = (
        pre_attempt003_freeze_root / _ATTEMPT003_EXECUTION_FREEZE_PACKAGE
    )
    if (
        attempt003_freeze_package.exists()
        or attempt003_freeze_package.is_symlink()
    ):
        shutil.rmtree(attempt003_freeze_package)

    attempt003_authorization_package = (
        pre_attempt003_freeze_root / _ATTEMPT003_AUTHORIZATION_PACKAGE
    )
    if (
        attempt003_authorization_package.exists()
        or attempt003_authorization_package.is_symlink()
    ):
        shutil.rmtree(attempt003_authorization_package)

    previous: dict[str, Path] = {}
    for module_name, module in tuple(sys.modules.items()):
        module_file = getattr(module, "__file__", None)
        if module_file is None or not hasattr(module, "ROOT"):
            continue
        filename = Path(module_file).name
        replacement: Path | None = None
        if filename in _PRE_CALLSITE_TEST_FILES:
            replacement = pre_callsite_root
        elif filename in _PRE_AUTHORIZATION_TEST_FILES:
            replacement = pre_authorization_root
        elif filename in _PRE_ATTEMPT003_FREEZE_TEST_FILES:
            replacement = pre_attempt003_freeze_root
        if replacement is None:
            continue
        previous[module_name] = module.ROOT
        module.ROOT = replacement

    yield

    for module_name, original_root in previous.items():
        module = sys.modules.get(module_name)
        if module is not None:
            module.ROOT = original_root
