method:
  name: fixedpred
  eta: 0.1
  inference_steps: 10

search:
  grid:
    - {eta: 0.1, inference_steps: 1}
    - {eta: 0.1, inference_steps: 5}
    - {eta: 0.1, inference_steps: 10}
    - {eta: 0.3, inference_steps: 1}
    - {eta: 0.3, inference_steps: 5}
    - {eta: 0.3, inference_steps: 10}
    - {eta: 0.5, inference_steps: 5}
    - {eta: 0.5, inference_steps: 10}
    - {eta: 1.0, inference_steps: 6}
